name: Build job

on:
  # Everyday at 21:00 UTC
  schedule:
    - cron: '0 10,21 * * *'
    
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

env:
  REPO_NAME: recloudstream/cloudstream

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          repository: '${{ env.REPO_NAME }}'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          repository: '${{ env.REPO_NAME }}'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
          
      - name: Get current commit count, and count from previous commit
        run:  |
          set -e
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          echo "CURRENT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          
          echo "COMMIT_COUNT_DIFF=$(($commit_count - $prev_commit_count))" >> $GITHUB_ENV
        
      - name: Exit if there are no new commits since last release
        if: env.COMMIT_COUNT_DIFF < 1
        run: exit 100
        
      - name: Get previous commit count, and set up commit logs
        if: env.COMMIT_COUNT_DIFF > 0
        run:  |
          set -e
          
          current_sha=${{ env.CURRENT_SHA }}
          commit_count_diff=${{ env.COMMIT_COUNT_DIFF }}
          
          prev_release_sha=$(git rev-parse --short $current_sha~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV
          
          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ env.REPO_NAME }}/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set checks for prerelease updates to true by default
        run: |
          sed -i "s/R\.string\.prerelease_update_key), false))/R\.string\.prerelease_update_key), true))/" app/src/main/java/com/lagradost/cloudstream3/utils/InAppUpdater.kt
      
      - name: Update prerelease_commit_hash
        run: |
          COMMIT_HASH="$(git log -1 --format='%H')"
          sed -i "s/<string name=\"prerelease_commit_hash\" translatable=\"false\">unknown_prerelease<\/string>/<string name=\"prerelease_commit_hash\">$COMMIT_HASH<\/string>/g" app/src/main/res/values/strings.xml
      
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/prerelease_keystore.keystore
          
      - name: Run Gradle
        run: ./gradlew app:assemblePrerelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          
      - name: Clean up build artifacts
        run: |
          set -e
          
          cp app/build/outputs/apk/prerelease/app-prerelease.apk Cloudstream3-r${{ env.COMMIT_COUNT }}.apk
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Cloudstream r${{ env.COMMIT_COUNT }}
          body: |
            # Pre-release
            
            https://github.com/${{ env.REPO_NAME }}/compare/${{ env.PREV_RELEASE_SHA }}...${{ env.CURRENT_SHA }}
            
            ${{ env.COMMIT_LOGS }}
            
          files: |
            Cloudstream3-r${{ env.COMMIT_COUNT }}.apk
          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 12
          delete_tags: true
